# Generated by Django 5.0.4 on 2024-05-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('channel_id', models.CharField(max_length=255, unique=True, verbose_name='チャンネルID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '登録チャンネル',
                'verbose_name_plural': '登録チャンネル',
            },
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('picture_url', models.URLField(blank=True, max_length=1024, verbose_name='プロフィール画像URL')),
                ('line_id', models.CharField(max_length=255, unique=True, verbose_name='LINE ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'LINEユーザー',
                'verbose_name_plural': 'LINEユーザー',
            },
        ),
    ]
